FROM python:3.8-buster
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN mkdir -p /flashcards
WORKDIR /flashcards
COPY requirements.txt /flashcards/
RUN pip install -r requirements.txt
COPY . /flashcards/

EXPOSE 8000

CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]