apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: flashcards
  name: flashcards
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flashcards
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: flashcards
    spec:
      containers:
        - args:
            - python
            - manage.py
            - runserver
            - 0.0.0.0:8000
          image: flashcards
          name: flashcards
          ports:
            - containerPort: 8000
          resources: {}
          tty: true
      restartPolicy: Always
status: {}
